import { Resource } from './types';

export const AI_ML: Resource[] = [
  {
    id: 'ollama',
    name: 'Ollama - Run LLMs Locally',
    description: 'Run Llama, Mistral, other LLMs on your computer. No cloud costs, no API keys. Download, run locally.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'advanced'],
    url: 'https://ollama.ai',
    howtoaccess: 'Download from ollama.ai, then: ollama run llama2',
    usecase: 'Experiment with LLMs, build AI apps locally, learn how models work',
  },
  {
    id: 'lm-studio',
    name: 'LM Studio - LLMs on Your Computer',
    description: 'Desktop app to download and run open-source LLMs locally. User-friendly, no terminal needed.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable'],
    url: 'https://lmstudio.ai',
    howtoaccess: 'Download from lmstudio.ai, open the app',
    usecase: 'Run Llama, Mistral locally with GUI interface',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    description: 'Google\'s machine learning framework. Open source. Build neural networks, train models, deploy AI.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://github.com/tensorflow/tensorflow',
    github: { owner: 'tensorflow', repo: 'tensorflow' },
    howtoaccess: 'pip install tensorflow or clone github.com/tensorflow/tensorflow',
    usecase: 'Build machine learning and deep learning models',
  },
  {
    id: 'pytorch',
    name: 'PyTorch',
    description: 'Facebook\'s machine learning framework. Used by researchers worldwide. Intuitive, powerful, free.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://github.com/pytorch/pytorch',
    github: { owner: 'pytorch', repo: 'pytorch' },
    howtoaccess: 'pip install torch or clone github.com/pytorch/pytorch',
    usecase: 'Build neural networks, computer vision, NLP models',
  },
  {
    id: 'scikit-learn',
    name: 'scikit-learn',
    description: 'Python machine learning library. Easy-to-use algorithms for classification, regression, clustering.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://github.com/scikit-learn/scikit-learn',
    github: { owner: 'scikit-learn', repo: 'scikit-learn' },
    howtoaccess: 'pip install scikit-learn',
    usecase: 'Quick machine learning without deep learning complexity',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Transformers',
    description: 'Access 100k+ pre-trained models. BERT, GPT, image models. Download and use locally, or via API.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://github.com/huggingface/transformers',
    github: { owner: 'huggingface', repo: 'transformers' },
    howtoaccess: 'pip install transformers or use Hugging Face Hub',
    usecase: 'Use state-of-the-art models for NLP, vision',
  },
  {
    id: 'google-colab',
    name: 'Google Colab - Free GPU Notebooks',
    description: 'Free Jupyter notebooks with GPU access. No signup required (well, Google account). Train models for free.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://colab.research.google.com',
    howtoaccess: 'Visit colab.research.google.com (sign in to Google)',
    usecase: 'Train machine learning models with free GPU',
  },
  {
    id: 'kaggle',
    name: 'Kaggle - Datasets & Notebooks',
    description: 'Million datasets, code notebooks, competitions. Free tier with GPU access. Learn from community.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'no-signup', 'intermediate'],
    url: 'https://www.kaggle.com',
    howtoaccess: 'Sign up free at kaggle.com',
    usecase: 'Find datasets, learn from community notebooks, run experiments',
  },
  {
    id: 'replicate',
    name: 'Replicate - Run AI Models',
    description: 'Run open-source AI models via simple API. First month free, then pay-as-you-go. No model training needed.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'intermediate'],
    url: 'https://replicate.com',
    howtoaccess: 'Sign up at replicate.com, get free credits',
    usecase: 'Use stable diffusion, CLIP, LLMs via API',
  },
  {
    id: 'huggingface-hub',
    name: 'Hugging Face Hub - Model Repository',
    description: 'Download any of 100k models. Llama, BERT, Stable Diffusion, etc. Free downloads.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'open-source', 'no-signup'],
    url: 'https://huggingface.co/models',
    howtoaccess: 'Visit huggingface.co/models, browse and download',
    usecase: 'Find pre-trained models for any AI task',
  },
  {
    id: 'langchain',
    name: 'LangChain - Build LLM Apps',
    description: 'Python framework for building applications with LLMs. Chain prompts, integrate APIs, deploy quickly.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://github.com/langchain-ai/langchain',
    github: { owner: 'langchain-ai', repo: 'langchain' },
    howtoaccess: 'pip install langchain',
    usecase: 'Build chatbots, RAG systems, AI agents',
  },
  {
    id: 'stable-diffusion-webui',
    name: 'Stable Diffusion WebUI',
    description: 'Generate images locally with Stable Diffusion. Download, run, no cloud needed.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable'],
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    github: { owner: 'AUTOMATIC1111', repo: 'stable-diffusion-webui' },
    howtoaccess: 'Clone repo, install requirements, run python',
    usecase: 'Generate images with AI locally',
  },
  {
    id: 'openai-cookbook',
    name: 'OpenAI Cookbook - Learning Examples',
    description: 'GitHub repo with examples using OpenAI APIs. Learn best practices from OpenAI.',
    category: 'ai-ml',
    type: 'guide',
    tags: ['free', 'open-source', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://github.com/openai/openai-cookbook',
    github: { owner: 'openai', repo: 'openai-cookbook' },
    howtoaccess: 'Clone repo, read examples, copy code',
    usecase: 'Learn how to use ChatGPT API effectively',
  },
  {
    id: 'papers-with-code',
    name: 'Papers with Code',
    description: 'Research papers linked with code implementations. Free access to latest AI research.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'no-signup', 'advanced'],
    url: 'https://paperswithcode.com',
    howtoaccess: 'Browse paperswithcode.com, read papers + code',
    usecase: 'Learn latest AI research with runnable code',
  },
  {
    id: 'arxiv',
    name: 'arXiv - AI Research Papers',
    description: 'Free archive of AI and ML research papers. Pre-prints before publication.',
    category: 'ai-ml',
    type: 'guide',
    tags: ['free', 'no-signup', 'advanced'],
    url: 'https://arxiv.org/list/cs.AI/recent',
    howtoaccess: 'Visit arxiv.org, search papers, download PDFs',
    usecase: 'Read latest AI research from researchers worldwide',
  },
  {
    id: 'deepseek-api',
    name: 'DeepSeek - Free LLM API',
    description: 'Chinese AI company offering free API credits. Alternative to OpenAI.',
    category: 'ai-ml',
    type: 'tool',
    tags: ['free', 'intermediate'],
    url: 'https://www.deepseek.com',
    howtoaccess: 'Sign up at deepseek.com, get free credits',
    usecase: 'Use LLM API for chatbots, text generation',
  },
  {
    id: 'vercel-ai-sdk',
    name: 'Vercel AI SDK',
    description: 'JavaScript SDK for building AI apps. Works with any LLM provider. Streaming, edge functions support.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://github.com/vercel/ai',
    github: { owner: 'vercel', repo: 'ai' },
    howtoaccess: 'npm install ai',
    usecase: 'Build AI chat apps with Next.js',
  },
  {
    id: 'anthropic-sdk',
    name: 'Anthropic Python SDK - Claude API',
    description: 'Official SDK for Claude API. Build with Claude locally.',
    category: 'ai-ml',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://github.com/anthropics/anthropic-sdk-python',
    github: { owner: 'anthropics', repo: 'anthropic-sdk-python' },
    howtoaccess: 'pip install anthropic',
    usecase: 'Use Claude in your Python apps (get free credits)',
  },
];
