import { Resource } from './types';

export const BUSINESS: Resource[] = [
  {
    id: 'startup-school',
    name: 'Startup School by Y Combinator',
    description: 'Free online startup course from Y Combinator. Learn business fundamentals, talk to founders.',
    category: 'business',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://www.startupschool.org',
    howtoaccess: 'Visit startupschool.org, watch videos free',
    usecase: 'Learn startup basics from YC',
  },
  {
    id: 'lean-canvas',
    name: 'Lean Canvas - Business Model Template',
    description: 'Free business plan template. One-page format. Download and fill in.',
    category: 'business',
    type: 'guide',
    tags: ['free', 'downloadable', 'beginner'],
    url: 'https://leanstack.com',
    howtoaccess: 'Visit leanstack.com, download template',
    usecase: 'Plan your startup in one page',
  },
  {
    id: 'business-model-canvas',
    name: 'Business Model Canvas - Template',
    description: 'Strategic business planning template. Free PDF download.',
    category: 'business',
    type: 'guide',
    tags: ['free', 'downloadable', 'beginner'],
    url: 'https://www.strategyzer.com/canvas/business-model-canvas',
    howtoaccess: 'Visit strategyzer.com, download free',
    usecase: 'Design your business model visually',
  },
  {
    id: 'github-licenses',
    name: 'GitHub Licenses - Choose Free License',
    description: 'Free open-source licenses. MIT, Apache, GPL, etc. Choose and download.',
    category: 'business',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://github.com/licenses',
    howtoaccess: 'Visit github.com/licenses, read and copy',
    usecase: 'License your open-source project',
  },
  {
    id: 'creative-commons',
    name: 'Creative Commons - Free Licensing',
    description: 'Free content licenses. Decide how others can use your work.',
    category: 'business',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://creativecommons.org',
    howtoaccess: 'Visit creativecommons.org, choose license',
    usecase: 'License creative work and content',
  },
  {
    id: 'stripe-atlas',
    name: 'Stripe Atlas - Form a Company',
    description: 'Guide to forming a startup company. Legal documents templates.',
    category: 'business',
    type: 'guide',
    tags: ['free', 'beginner'],
    url: 'https://stripe.com/atlas/guides',
    howtoaccess: 'Visit stripe.com/atlas, read guides',
    usecase: 'Understand how to legally form company',
  },
  {
    id: 'notion-free',
    name: 'Notion - All-in-One Workspace (Free Tier)',
    description: 'Free Notion workspace for planning, docs, databases. Generous free tier.',
    category: 'business',
    type: 'tool',
    tags: ['free', 'beginner'],
    url: 'https://www.notion.so',
    howtoaccess: 'Sign up free at notion.so',
    usecase: 'Organize startup planning, docs, tasks',
  },
  {
    id: 'airtable-free',
    name: 'Airtable - Database Spreadsheet (Free Tier)',
    description: 'Free tier for startups. Build databases, track projects, collaborate.',
    category: 'business',
    type: 'tool',
    tags: ['free', 'beginner'],
    url: 'https://www.airtable.com',
    howtoaccess: 'Sign up free at airtable.com',
    usecase: 'Track customers, projects, inventory',
  },
  {
    id: 'canva-startup',
    name: 'Canva - Design Presentations (Free Tier)',
    description: 'Create pitch decks and materials. Free tier available.',
    category: 'business',
    type: 'tool',
    tags: ['free', 'beginner'],
    url: 'https://www.canva.com',
    howtoaccess: 'Sign up free at canva.com',
    usecase: 'Design pitch decks, social media graphics',
  },
  {
    id: 'loom-free',
    name: 'Loom - Record Videos (Free Tier)',
    description: 'Record screen video demos, pitch videos. Free with limits.',
    category: 'business',
    type: 'tool',
    tags: ['free', 'beginner'],
    url: 'https://www.loom.com',
    howtoaccess: 'Sign up free, install browser extension',
    usecase: 'Record product demos, team videos',
  },
];
