import { Resource } from './types';

export const DESIGN: Resource[] = [
  {
    id: 'penpot',
    name: 'Penpot - Open Source Figma Alternative',
    description: 'Free, self-hosted design tool. Same capabilities as Figma without $120/year cost. Clone repo or use cloud version.',
    category: 'design',
    type: 'alternative',
    tags: ['free', 'open-source', 'downloadable', 'self-hosted'],
    url: 'https://github.com/penpot/penpot',
    github: { owner: 'penpot', repo: 'penpot' },
    howtoaccess: 'Self-host via Docker or use free cloud at penpot.app',
    usecase: 'Design UIs, wireframes, prototypes without cost',
  },
  {
    id: 'gimp',
    name: 'GIMP - Free Photoshop Alternative',
    description: 'Download free image editor. Raster graphics, photo editing, layers. No subscription.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://www.gimp.org',
    howtoaccess: 'Download from gimp.org for Windows/Mac/Linux',
    usecase: 'Edit photos, create graphics, design banners',
  },
  {
    id: 'inkscape',
    name: 'Inkscape - Free Illustrator Alternative',
    description: 'Download free vector graphics editor. Create logos, icons, illustrations. No cost.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://inkscape.org',
    howtoaccess: 'Download from inkscape.org',
    usecase: 'Create vector graphics, logos, icons',
  },
  {
    id: 'unsplash',
    name: 'Unsplash - Free Stock Photos',
    description: 'Millions of free photos. Download without signup or watermarks. Use for any project.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://unsplash.com',
    howtoaccess: 'Visit unsplash.com, search, download',
    usecase: 'Find beautiful photos for websites, apps',
  },
  {
    id: 'pexels',
    name: 'Pexels - Free Photos & Videos',
    description: 'Free stock photos and videos. No signup, no watermark. Commercial license included.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://www.pexels.com',
    howtoaccess: 'Visit pexels.com, download free',
    usecase: 'Get images and videos for projects',
  },
  {
    id: 'pixabay',
    name: 'Pixabay - Photos, Icons, Music',
    description: 'Free images, vectors, music. No credits needed. Large library.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://pixabay.com',
    howtoaccess: 'Visit pixabay.com, search and download',
    usecase: 'Find photos, illustrations, music',
  },
  {
    id: 'font-awesome',
    name: 'Font Awesome - Free Icons',
    description: '2000+ free icons. Font or SVG format. Use in any project.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'open-source', 'no-signup', 'beginner'],
    url: 'https://fontawesome.com',
    howtoaccess: 'Use CDN or npm install @fortawesome/fontawesome',
    usecase: 'Add icons to websites and apps',
  },
  {
    id: 'google-fonts',
    name: 'Google Fonts - Free Typography',
    description: '1000+ free fonts. Easy to embed in websites. No downloads needed.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://fonts.google.com',
    howtoaccess: 'Visit fonts.google.com, choose font, copy code',
    usecase: 'Add beautiful typography to websites',
  },
  {
    id: 'tailwind-ui',
    name: 'Tailwind CSS - Free Components',
    description: 'Utility-first CSS framework. Build designs fast. Free and open source.',
    category: 'design',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://tailwindcss.com',
    howtoaccess: 'npm install tailwindcss or use CDN',
    usecase: 'Design and style websites without writing CSS',
  },
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui - React Components',
    description: 'Copy-paste React components. Tailwind CSS + Radix. Free, open source on GitHub.',
    category: 'design',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable'],
    url: 'https://github.com/shadcn-ui/ui',
    github: { owner: 'shadcn-ui', repo: 'ui' },
    howtoaccess: 'Clone repo or use CLI: npx shadcn-ui@latest init',
    usecase: 'Build React apps with pre-made components',
  },
];
