import { Resource } from './types';

export const DEV_TOOLS: Resource[] = [
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Server-side JavaScript runtime. Clone the repo, build backends, APIs, and CLI tools. See how it\'s built and learn from production code.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://github.com/nodejs/node',
    github: { owner: 'nodejs', repo: 'node' },
    howtoaccess: 'git clone https://github.com/nodejs/node.git or download from https://nodejs.org',
    usecase: 'Build web servers, APIs, CLI tools, real-time apps',
  },
  {
    id: 'django',
    name: 'Django',
    description: 'Python web framework. Full-featured backend with ORM, admin panel, auth built-in. Great for learning web development fundamentals.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://github.com/django/django',
    github: { owner: 'django', repo: 'django' },
    howtoaccess: 'pip install django or clone https://github.com/django/django.git',
    usecase: 'Build full-stack web applications, RESTful APIs, CMS projects',
  },
  {
    id: 'flask',
    name: 'Flask',
    description: 'Lightweight Python web framework. Minimal and flexible - great for learning how web frameworks work from scratch.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://github.com/pallets/flask',
    github: { owner: 'pallets', repo: 'flask' },
    howtoaccess: 'pip install flask or clone the GitHub repo',
    usecase: 'Build lightweight web apps, APIs, microservices',
  },
  {
    id: 'expressjs',
    name: 'Express.js',
    description: 'Minimal Node.js web framework. Used by thousands of apps. Learn how to structure backend code professionally.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://github.com/expressjs/express',
    github: { owner: 'expressjs', repo: 'express' },
    howtoaccess: 'npm install express in your project',
    usecase: 'Build REST APIs, web servers, full-stack applications',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Powerful open-source database. Download, run locally, learn SQL and database design. Free forever.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://www.postgresql.org/download/',
    howtoaccess: 'Download from postgresql.org or docker pull postgres',
    usecase: 'Store and query data for any web/mobile app',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Lightweight SQL database that runs in one file. Perfect for learning databases or building local-first apps.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://www.sqlite.org/download.html',
    howtoaccess: 'Download executable or npm install sqlite3',
    usecase: 'Learn databases, prototype apps, build desktop applications',
  },
  {
    id: 'mongodb-ce',
    name: 'MongoDB Community Edition',
    description: 'NoSQL database you can run yourself. Download, run locally, experiment with document-based data storage.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://www.mongodb.com/try/download/community',
    howtoaccess: 'Download from MongoDB.com or docker pull mongo',
    usecase: 'Build apps with flexible JSON-like data storage',
  },
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    description: 'Industry-standard code editor. Free, lightweight, thousands of extensions. Download and start coding immediately.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'downloadable', 'beginner'],
    url: 'https://code.visualstudio.com',
    howtoaccess: 'Download installer from https://code.visualstudio.com',
    usecase: 'Write all your code - JavaScript, Python, Go, etc.',
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Version control system. Download, learn how to save your code progress, collaborate with others, and understand software development workflow.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://git-scm.com',
    howtoaccess: 'Download from git-scm.com or use package manager',
    usecase: 'Track code changes, work with GitHub, collaborate on projects',
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerization platform. Download, learn to package apps reproducibly. Run the exact same environment everywhere.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://www.docker.com',
    howtoaccess: 'Download Docker Desktop from docker.com or use CLI',
    usecase: 'Run databases, services, deploy apps consistently',
  },
  {
    id: 'postman',
    name: 'Postman',
    description: 'Test and develop APIs. Download the app, test your backend APIs locally, learn how HTTP requests work.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://www.postman.com/downloads/',
    howtoaccess: 'Download from postman.com',
    usecase: 'Test APIs before frontend integration, debug backend issues',
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    description: 'Open-source API client like Postman. Download, lightweight, test your APIs locally.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable'],
    url: 'https://github.com/Kong/insomnia',
    github: { owner: 'Kong', repo: 'insomnia' },
    howtoaccess: 'Download from insomnia.rest or clone the repo',
    usecase: 'Test and debug APIs',
  },
  {
    id: 'ollama',
    name: 'Ollama - Run LLMs Locally',
    description: 'Run large language models on your computer. Download, run Llama, Mistral, or other open models. Zero cloud costs.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'downloadable', 'open-source', 'advanced'],
    url: 'https://ollama.ai',
    howtoaccess: 'Download from ollama.ai, then run: ollama run llama2',
    usecase: 'Experiment with LLMs, build AI apps locally, learn how models work',
  },
  {
    id: 'vercel-cli',
    name: 'Vercel CLI',
    description: 'Deploy Next.js apps and Node.js backends instantly from command line. Free tier works perfectly.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'downloadable', 'beginner', 'intermediate'],
    url: 'https://vercel.com/docs/cli',
    howtoaccess: 'npm install -g vercel then vercel deploy',
    usecase: 'Deploy your web projects live (free)',
  },
  {
    id: 'railway-guide',
    name: 'Railway - $5/month Free Tier',
    description: 'Deploy Node, Python, Go apps with generous free tier. Full guide on how to get $5/month free credits.',
    category: 'dev',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://railway.app/docs',
    howtoaccess: 'Sign up at railway.app (free tier)',
    usecase: 'Deploy full-stack apps (backend + database)',
  },
  {
    id: 'render-free',
    name: 'Render - Free Tier Hosting',
    description: 'Deploy web services and databases for free. Step-by-step: create account, connect GitHub, deploy.',
    category: 'dev',
    type: 'guide',
    tags: ['free', 'beginner'],
    url: 'https://render.com/docs',
    howtoaccess: 'Sign up free at render.com',
    usecase: 'Host Node/Python backends, databases live (free)',
  },
  {
    id: 'github-cli',
    name: 'GitHub CLI',
    description: 'Manage GitHub from command line. Clone repos, create PRs, work with issues without opening browser.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://github.com/cli/cli',
    github: { owner: 'cli', repo: 'cli' },
    howtoaccess: 'Download from github.com/cli/cli or package manager',
    usecase: 'Streamline GitHub workflow from terminal',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    description: 'High-performance web server and reverse proxy. Learn production server architecture.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'advanced'],
    url: 'https://github.com/nginx/nginx',
    github: { owner: 'nginx', repo: 'nginx' },
    howtoaccess: 'Download from nginx.org or apt-get/brew install nginx',
    usecase: 'Host websites, load balance, serve static files',
  },
  {
    id: 'react',
    name: 'React (Facebook Library)',
    description: 'UI library. Clone the repo, see how Facebook builds React, contribute to open source.',
    category: 'dev',
    type: 'github-repo',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://github.com/facebook/react',
    github: { owner: 'facebook', repo: 'react' },
    howtoaccess: 'npx create-react-app or clone https://github.com/facebook/react',
    usecase: 'Build interactive user interfaces',
  },
  {
    id: 'tailwind-css',
    name: 'Tailwind CSS',
    description: 'Utility-first CSS framework. Open source, no signup needed. Style apps fast with minimal code.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://tailwindcss.com',
    howtoaccess: 'npm install tailwindcss or use CDN link',
    usecase: 'Style your web apps beautifully and quickly',
  },
  {
    id: 'jsonapi',
    name: 'JSONPlaceholder - Fake API',
    description: 'Free fake REST API for testing. No signup, no auth needed. Perfect for prototyping without a backend.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://jsonplaceholder.typicode.com',
    howtoaccess: 'No download needed - just use the URL in fetch()',
    usecase: 'Test frontend code, learn HTTP requests',
  },
  {
    id: 'gist',
    name: 'GitHub Gist',
    description: 'Share code snippets and small projects instantly. Free, no upload limits, easy to embed.',
    category: 'dev',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://gist.github.com',
    howtoaccess: 'Visit gist.github.com and create',
    usecase: 'Share code snippets, prototypes, examples',
  },
];
