import { Resource } from './types';

export const HARDWARE: Resource[] = [
  {
    id: 'freecad',
    name: 'FreeCAD - 3D Design Software',
    description: 'Free CAD software for 3D modeling. Download, learn 3D design, prepare files for 3D printing.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://www.freecadweb.org',
    howtoaccess: 'Download from freecadweb.org for any OS',
    usecase: 'Design 3D parts, learn CAD, prepare for 3D printing',
  },
  {
    id: 'openscad',
    name: 'OpenSCAD - 3D Modeling via Code',
    description: 'Design 3D objects using code. Parametric modeling. Free, open source.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate', 'advanced'],
    url: 'https://openscad.org',
    howtoaccess: 'Download from openscad.org',
    usecase: 'Create parametric 3D designs, prepare for 3D printing',
  },
  {
    id: 'thingiverse',
    name: 'Thingiverse - 3D Models',
    description: 'Millions of free 3D models for 3D printing. Download STL files. No signup needed.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://www.thingiverse.com',
    howtoaccess: 'Visit thingiverse.com, search, download STL',
    usecase: 'Find models to 3D print (cases, parts, toys, etc.)',
  },
  {
    id: 'printables',
    name: 'Printables - 3D Models',
    description: 'Modern Thingiverse alternative. Free 3D models from designers.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://www.printables.com',
    howtoaccess: 'Visit printables.com, download files',
    usecase: 'Find and download 3D models for printing',
  },
  {
    id: 'arduino-ide',
    name: 'Arduino IDE - Microcontroller Programming',
    description: 'Download free IDE for Arduino. Write code, upload to boards. Beginner-friendly.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://www.arduino.cc/en/software',
    howtoaccess: 'Download from arduino.cc',
    usecase: 'Program Arduino boards for IoT projects',
  },
  {
    id: 'raspberry-pi-os',
    name: 'Raspberry Pi OS - Free Operating System',
    description: 'Download Linux OS for Raspberry Pi. Lightweight, free, open source.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'beginner'],
    url: 'https://www.raspberrypi.com/software/',
    howtoaccess: 'Download Raspberry Pi Imager and install',
    usecase: 'Run operating system on Raspberry Pi single-board computer',
  },
  {
    id: 'esp32-development',
    name: 'ESP32 - $5 WiFi Microcontroller',
    description: 'Cheap microcontroller with WiFi. Program with Arduino IDE. Open source hardware.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'beginner', 'intermediate'],
    url: 'https://www.espressif.com/en/products/socs/esp32',
    howtoaccess: 'Order from AliExpress ($5-10), program with Arduino IDE',
    usecase: 'Build WiFi IoT projects cheaply',
  },
  {
    id: 'micropython',
    name: 'MicroPython - Python on Microcontrollers',
    description: 'Run Python on Arduino/ESP32/Raspberry Pi. Download, install, code.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'intermediate'],
    url: 'https://micropython.org',
    howtoaccess: 'Download firmware from micropython.org, flash to board',
    usecase: 'Program microcontrollers in Python',
  },
  {
    id: 'kicad',
    name: 'KiCAD - Circuit Design Software',
    description: 'Free electronic circuit design. Schematic and PCB design. Open source.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'open-source', 'downloadable', 'advanced'],
    url: 'https://www.kicad.org',
    howtoaccess: 'Download from kicad.org',
    usecase: 'Design circuit schematics and PCBs',
  },
  {
    id: 'wokwi',
    name: 'Wokwi - Arduino/ESP32 Simulator',
    description: 'Simulate Arduino and ESP32 in browser. No hardware needed to learn. Free.',
    category: 'hardware',
    type: 'tool',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://wokwi.com',
    howtoaccess: 'Visit wokwi.com, start simulating',
    usecase: 'Learn Arduino/microcontrollers before buying hardware',
  },
];
