import { Resource } from './types';

export const LEARNING: Resource[] = [
  {
    id: 'traversy-yt',
    name: 'Traversy Media - YouTube',
    description: 'Hundreds of free coding tutorials. React, Node, Python, web dev, and more. No signup, just watch on YouTube.',
    category: 'learning',
    type: 'tutorial',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://www.youtube.com/@TraversyMedia',
    howtoaccess: 'Go to YouTube channel and start watching (free)',
    usecase: 'Learn web development, follow along with live coding',
  },
  {
    id: 'net-ninja-yt',
    name: 'The Net Ninja - YouTube',
    description: 'Web development and design tutorials. JavaScript, React, Vue, CSS, design fundamentals. Free YouTube channel.',
    category: 'learning',
    type: 'tutorial',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://www.youtube.com/@NetNinja',
    howtoaccess: 'Visit YouTube channel, pick a course playlist',
    usecase: 'Learn frontend and backend development',
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp - YouTube',
    description: 'Full-length courses on YouTube: 4-hour React course, 12-hour Python course, web dev bootcamps. Completely free.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://www.youtube.com/@freecodecamp',
    howtoaccess: 'Watch on YouTube (free) - no signup needed',
    usecase: 'Complete structured courses from basics to advanced',
  },
  {
    id: 'eloquent-js',
    name: 'Eloquent JavaScript - Free PDF',
    description: 'Free online book teaching JavaScript deeply. Read in browser, download PDF. High quality, written by professional.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://eloquentjavascript.net',
    howtoaccess: 'Read free on website or download PDF',
    usecase: 'Learn JavaScript fundamentals deeply',
  },
  {
    id: 'mdn-docs',
    name: 'MDN Web Docs - Mozilla',
    description: 'The authority on web technologies. HTML, CSS, JavaScript reference. Guides and tutorials. Free.',
    category: 'learning',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner', 'intermediate', 'advanced'],
    url: 'https://developer.mozilla.org',
    howtoaccess: 'Visit MDN.com - bookmark it',
    usecase: 'Look up HTML tags, CSS properties, JavaScript APIs',
  },
  {
    id: 'react-docs',
    name: 'React Official Docs',
    description: 'React\'s official documentation. Learn from the creators. Excellent interactive tutorials and API reference.',
    category: 'learning',
    type: 'guide',
    tags: ['free', 'no-signup', 'intermediate'],
    url: 'https://react.dev',
    howtoaccess: 'Visit react.dev - read and follow tutorials',
    usecase: 'Learn React properly from official source',
  },
  {
    id: 'nextjs-learn',
    name: 'Next.js Learn Course - Official',
    description: 'Official Next.js course. Build a dashboard app. Free, interactive, from Vercel team.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'intermediate'],
    url: 'https://nextjs.org/learn',
    howtoaccess: 'Visit nextjs.org/learn and start course',
    usecase: 'Learn Next.js by building real app',
  },
  {
    id: 'nodejs-docs',
    name: 'Node.js Official Docs',
    description: 'Complete Node.js documentation. API reference, guides on servers, databases, modules. Free.',
    category: 'learning',
    type: 'guide',
    tags: ['free', 'no-signup', 'intermediate'],
    url: 'https://nodejs.org/docs',
    howtoaccess: 'Visit nodejs.org/docs',
    usecase: 'Reference for Node APIs and how to build servers',
  },
  {
    id: 'python-docs',
    name: 'Python Official Tutorial',
    description: 'Official Python tutorial from Python.org. Comprehensive guide to the language.',
    category: 'learning',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://docs.python.org/3/tutorial/',
    howtoaccess: 'Visit docs.python.org/3/tutorial',
    usecase: 'Learn Python from official source',
  },
  {
    id: 'automate-boring',
    name: 'Automate the Boring Stuff with Python',
    description: 'Free online book. Learn practical Python for real-world tasks. Downloadable PDF or read online.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://automatetheboringstuff.com',
    howtoaccess: 'Read free on website or download PDF',
    usecase: 'Learn Python automation and practical programming',
  },
  {
    id: 'mit-ocw',
    name: 'MIT OpenCourseWare',
    description: 'Real MIT courses, free. Computer science, algorithms, databases. Same content MIT students see.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner', 'intermediate', 'advanced'],
    url: 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/',
    howtoaccess: 'Visit MIT OCW, watch lectures (video + notes)',
    usecase: 'Learn CS fundamentals from MIT professors',
  },
  {
    id: 'stanford-cs106',
    name: 'Stanford CS106A - Programming Methodology',
    description: 'Complete Stanford intro CS course. Lectures available free online.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://see.stanford.edu/Course/CS106A',
    howtoaccess: 'Watch free on Stanford Engineering Everywhere',
    usecase: 'Learn computer science fundamentals',
  },
  {
    id: 'you-dont-know-js',
    name: 'You Don\'t Know JS - GitHub',
    description: 'Free online book series on JavaScript. All content on GitHub, licensed free.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'open-source', 'no-signup', 'intermediate'],
    url: 'https://github.com/getify/You-Dont-Know-JS',
    howtoaccess: 'Read on GitHub, clone repo, or read on 2ndedition.ydkjs.dev',
    usecase: 'Deep dive into JavaScript concepts',
  },
  {
    id: 'dev-to',
    name: 'Dev.to - Developer Community',
    description: 'Community of developers sharing tutorials and articles. Huge library of free guides.',
    category: 'learning',
    type: 'tutorial',
    tags: ['free', 'no-signup', 'beginner', 'intermediate', 'advanced'],
    url: 'https://dev.to',
    howtoaccess: 'Visit dev.to, search topics (optional signup)',
    usecase: 'Read latest dev tutorials from community',
  },
  {
    id: 'css-tricks',
    name: 'CSS-Tricks - Web Design Tips',
    description: 'Articles on CSS, web design, frontend development. Hundreds of free guides.',
    category: 'learning',
    type: 'tutorial',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://css-tricks.com',
    howtoaccess: 'Visit css-tricks.com, read articles (free)',
    usecase: 'Learn CSS tips, tricks, and best practices',
  },
  {
    id: 'web-dev-google',
    name: 'web.dev by Google',
    description: 'Google\'s guide to modern web development. Performance, accessibility, PWAs. Free.',
    category: 'learning',
    type: 'guide',
    tags: ['free', 'no-signup', 'beginner', 'intermediate'],
    url: 'https://web.dev',
    howtoaccess: 'Visit web.dev, read articles and guides',
    usecase: 'Learn web best practices from Google',
  },
  {
    id: 'github-skills',
    name: 'GitHub Skills - Free Interactive Lessons',
    description: 'GitHub\'s free interactive courses. Git, GitHub, coding skills. Takes 15-30 minutes each.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://skills.github.com',
    howtoaccess: 'Visit skills.github.com, take free courses',
    usecase: 'Learn Git and GitHub workflows',
  },
  {
    id: 'codecombat',
    name: 'CodeCombat - Learn to Code Playing Games',
    description: 'Learn programming through game-based lessons. Free levels available.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'beginner'],
    url: 'https://codecombat.com',
    howtoaccess: 'Visit codecombat.com, sign up free',
    usecase: 'Learn JavaScript, Python through games',
  },
  {
    id: 'khan-academy',
    name: 'Khan Academy - Programming',
    description: 'Free courses on computer science and programming. Video-based learning.',
    category: 'learning',
    type: 'course',
    tags: ['free', 'no-signup', 'beginner'],
    url: 'https://www.khanacademy.org/computing/computer-programming',
    howtoaccess: 'Visit Khan Academy (free signup)',
    usecase: 'Learn programming basics',
  },
];
